### ISSUE TITLE
Warning: Invalid argument supplied for foreach() 

### ISSUE THREAD

**Issue by guilhermeprokisch** [froger-me/wp-weixin#1]
I'm receving this error, when I try to install the plugin

supplied for foreach() in /var/www/html/wp-content/plugins/wp-weixin-master/inc/class-wp-weixin-settings.php on line 77

Warning: Invalid argument supplied for foreach() in /var/www/html/wp-content/plugins/wp-weixin-master/inc/class-wp-weixin-settings.php on line 77

Warning: Invalid argument supplied for foreach() in /var/www/html/wp-content/plugins/wp-weixin-master/inc/class-wp-weixin-settings.php on line 77

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/wp-weixin-master/inc/class-wp-weixin-settings.php:77) in /var/www/html/wp-admin/includes/misc.php on line 1126

**Comment by froger-me** [comment]
fix deployed
