### ISSUE TITLE
Token authentication fail for WeChat Responder Settings

### ISSUE THREAD

**Issue by Theo88** [froger-me/wp-weixin#11]
Hello,

I saw your previous post on this issue: https://github.com/froger-me/wp-weixin/issues/2

I have the exact same problem,

Could you please elaborate the fix :-)

you say: "Was an error in the rewrites "

Thank you

Theo

**Comment by froger-me** [comment]
Hello @Theo88  - the rewrites issue has been fixed. This error occurs when there is a configuration issue.
