### ISSUE TITLE
跳转错误问题

### ISSUE THREAD

**Issue by monyuan** [froger-me/wp-weixin#12]
前提：设置为强制关注微信公众号

复现：

未关注者使用微信浏览器访问网站，跳转到登陆被重定向到127.0.0.1

**Comment by froger-me** [comment]
Hello @monyuan 
I am sorry I do not understand the issue. Would there be a way for you to give me a method to reproduce it, step by step?

**Comment by froger-me** [comment]
Hello @monyuan 
Just to let you know, if this issue does not receive more information before Feb 3 2020, it will be closed automatically.
Best regards,
Alex
