### ISSUE TITLE
Error generating QR Code

### ISSUE THREAD

**Issue by kimcheezz** [froger-me/wp-weixin#13]
the qrocde generator shows the error image picture when trying to generating a qrcode for classic browser. The following is the image address of said image

https://pierreledent.cn/wp-weixin/get-qrcode/hash/aHR0cHM6Ly9waWVycmVsZWRlbnQuY24vbXktYWNjb3VudC98YWNmNjAzYjcxZg--

when click on "WeChat QR Code Authentification" on the login page, it simply redirect me to :

https://pierreledent.cn/wp-weixin/wechat-auth

which resulted in a 404 error.

Thanks for the hard work.

**Comment by froger-me** [comment]
Hello @kimcheezz !
I have not only tested in my own environment but also with your website (https://pierreledent.cn/wp-weixin/wechat-auth/) and the QR Code does show.
On a side note, I noticed your theme is conflicting with how the fonts are being displayed: the theme in use, Divi, has the following:

```css
* {
    font-family: 'Prompt',Helvetica,Arial,Lucida,sans-serif!important;
}
```

This can, and indeed does, conflict with plugin's icons using icon fonts, for example. This particular issue can be fixed easily with a CSS override using the !important directive on problematic properties, but it also shows that some conflicts you may experience **can** be coming from conflicts with third party extensions.

**Comment by froger-me** [comment]
I'll leave the issue closed since I haven't been able to replicate the issue - feel free to re-open if this issue is still relevant.

**Comment by kimcheezz** [comment]
Hi Alex,

Thanks for the reply. The QR code does work after a few tries. I overwritten the font because I strangely don't have a typography option inside of my Divi settings. I won't be using any emoji on the frontend so it's something that I can live with for now. 

Thank you so much again!

Kim

⁣Get TypeApp for Android ​

**Comment by froger-me** [comment]
Hi Kim!

I mentioned the font issue because WP Weixin and companion plugins use the Weui font to display icons, which Divi conflicts with.

Aside from that, I am happy you figured out how to make the QR codes work! To be fair, WeChat is complex, and this complexity bleeds over the settings of the plugin. Keep up the good work!
