### ISSUE TITLE
redrect_uri is wrong

### ISSUE THREAD

**Issue by resuly** [froger-me/wp-weixin#18]
**Software Version**
WordPress 5.4
wp-weixin 1.3.11

The WeChat account is a verified "subscriber" account, which has access to obtain the user information.
![image](https://user-images.githubusercontent.com/3870826/78867558-a2927380-7a84-11ea-86e1-fed23f165989.png)

**Issues**
1. The responder is not working at all. No welcome message to new users.
2. The WeChat browser showing the redirect_uri is wrong, so the program can't the user information.

**My Setting**
![image](https://user-images.githubusercontent.com/3870826/78865735-82ad8080-7a81-11ea-846b-cbbbe83079c4.png)
This means that the Responder is connected successfully.

![image](https://user-images.githubusercontent.com/3870826/78866039-09625d80-7a82-11ea-9ee2-3edf8215b74b.png)
The safe domain is all set and ready to go.

![image](https://user-images.githubusercontent.com/3870826/78866291-783fb680-7a82-11ea-9123-fe5c1143409b.png)

**Comment by froger-me** [comment]
Hello @resuly ,
OAuth2 is not supported by Subscription accounts. Please see the last item in the table below:
![image](https://user-images.githubusercontent.com/3622456/78869556-5ab91f80-7a77-11ea-9896-d5a77ee8164d.png)
