### ISSUE TITLE
计算机扫描二维码登录时手机上的页面重定向

### ISSUE THREAD

**Issue by leadroy** [froger-me/wp-weixin#20]
我想在用户通过手机扫描PC二维码登录系统时，将手机上自动重新定位到my-Account页而不是现在的提示“验证成功".

我通过帮助文件看到使用:
apply_filters( 'wp_weixin_auth_redirect','/my-account/'); 

但是好像不起作用。不知什么地方出了问题。感谢！

**Comment by froger-me** [comment]
Hi @leadroy 
What is your filter code?
Do you mean you simply added `apply_filters( 'wp_weixin_auth_redirect','/my-account/');` somewhere and tested?
If yes, maybe you need the help of a programmer familiar with WordPress, or get familiar with how it works - here is where you could begin: [Difference between add_filter and apply_filters
](https://wordpress.stackexchange.com/questions/131786/difference-between-add-filter-and-apply-filters/131789)

I just tested the filter - it works as designed.

If you'd like me to build that custom code for you, feel free to send me a RMB 500 红包 on WeChat (3 hours of work max, RMB 200 per extra hour if needed).
