### ISSUE TITLE
有没有办法不启用微信身份认证，而实现在微信里面打开付款呢？

### ISSUE THREAD

**Issue by faifai8** [froger-me/wp-weixin#23]
因为启用微信身份认证的话，网页上注册的用户无法在微信上重新登录

**Comment by froger-me** [comment]
Users already registered on the webpage have the option to bind their account with their WeChat-authenticated account.
![img1](https://ps.w.org/wp-weixin/assets/screenshot-13.png?rev=198864)
![img3](https://ps.w.org/wp-weixin/assets/screenshot-10.png?rev=1988640)
![img2](https://ps.w.org/wp-weixin/assets/screenshot-14.png?rev=1988640)
![img4](https://ps.w.org/wp-weixin/assets/screenshot-11.png?rev=1988640)

**Comment by faifai8** [comment]
好的，谢谢！
