### ISSUE TITLE
way back from using wechat responder?

### ISSUE THREAD

**Issue by jagottsicher** [froger-me/wp-weixin#27]
As we understand the description, we can setup our own menues in Wordpress to be used in wechat, if we switsch to the wechat responder feature and setup the correspoding menues. That will overrule the actual menues set in Wechat Backend.

But Is there a way back? For a language switching menu (other php-based app) we already use the api. we can temporarily turn that app off, but after using the autorepsonder will we be able to switch back? 

another question is about using the auto responder and worpdress hostet menues. Can it be combined with the "Official Account menu language awareness"-feature. We are aiming to provide the menu in different languages depending on the user's wechat settings - including a "fallback"-language which is used when the user's langugae is not supported by us (e.g. Swedish or Spanish user see English menues, while Chinese see Chinese language. Do the menues also include the extended length of menue items?

We couldn't try, but can different languages in the menues be provided by usage of WPML or Polylang in Wechat? Or does the Language options for the different languages appear somehow in the menu options?

BTW: great set of tools accessing wechat api you did here! best and most "standarized" I have seen so far.

**Comment by froger-me** [comment]
Hi @jagottsicher - sorry for the late reply...

> But Is there a way back? For a language switching menu (other php-based app) we already use the api. we can temporarily turn that app off, but after using the autorepsonder will we be able to switch back?

I'd say yes, the menus in WeChat will react based on what app connected to the WeChat backend (whether your custom app or WordPress) broadcasted them

> another question is about using the auto responder and worpdress hostet menues. 

I am not sure to understand the question. WP Weixin's language awareness feature maps the language tag of a WPML-set menu with the language tag of the language of the user's WeChat account to decide what menu to send to whom.

Thank you for the praise! There are definitely better PHP libraries for that (easywechat comes to mind), but they are quite heavy for what I intended to build... Also, I couldn't find anything for WordPress that wasn't paid unsafe spaghetti code, so I cam up with that quickfix ; it could be definitely better, but time is the main issue (so pull requests are welcome haha!).

**Comment by jagottsicher** [comment]
Thumbs up again for the great plugin and the clearification.
