### ISSUE TITLE
How do I show the feed from wechat?

### ISSUE THREAD

**Issue by phillipswdc** [froger-me/wp-weixin#6]
How can I show the feed on our website.

**Comment by froger-me** [comment]
Hello @phillipswdc !
Could you please indicate which listed feature in the documentation you are referring to? 
If it is not in the documentation, would you mind elaborating further on your question?

**Comment by phillipswdc** [comment]
My client has an office in Shanghai and they have a feed (like twitter) we would like to show that feed on the website.

When I search from the app I can go to their page and it has a feed. 

Perkins+Will and they are called an official account. I would like to put the feed on their webpage.

Thanks!!

**Comment by phillipswdc** [comment]
Any ideas on this?

**Comment by froger-me** [comment]
Hi @phillipswdc !
This is not a feature supported by the plugin.
If there is any support in the future within the plugin itself, it will be through the API only for developers to develop a companion plugin (or possibly one I would develop just like WP Weixin Pay or Woo WeChatPay).
At this stage this not a priority but I'm adding it to the roadmap - thank you for the idea.

**Comment by phillipswdc** [comment]
Thank you!! Can you point me in the right direction to someway to get the feed from their account? I am a developer and don't mind rolling up my sleeves and helping out.
