### ISSUE TITLE
Openid not found

### ISSUE THREAD

**Issue by jazzi** [froger-me/wp-weixin#7]
Hi Froger, thanks for your work in advance.

I installed **wp-weixin** and **Woo WeChatPay**.

Domain has been registered in the Official account's backend.

The menu of WeChat Service account is linked to the website, when checkout, an error shows "User has authorized in Tencent browser but OPENID not found."

![openidnotfound](https://user-images.githubusercontent.com/1588914/64065704-4be9cf00-cc43-11e9-92c7-c326d8f69fbb.jpeg)

**The settings of my website backend**

![001](https://user-images.githubusercontent.com/1588914/64065966-1941d580-cc47-11e9-981c-7ff403797356.jpg)
![002](https://user-images.githubusercontent.com/1588914/64065967-19da6c00-cc47-11e9-9ab7-6a9cde82edf3.jpg)
![003](https://user-images.githubusercontent.com/1588914/64065969-1a730280-cc47-11e9-94c4-0a75e359e474.jpg)

If you want, an access to the website backend can be offered.
Thank you.

**Comment by jazzi** [comment]
Problem solved by **enable** WeChat Authentication. (启用微信身份认证）

**Comment by faifai8** [comment]
有没有办法不启用微信身份认证，而可以实现在微信里面打开付款呢？
