### ISSUE TITLE
H5 in mobile browser(Not just the wechat browser)

### ISSUE THREAD

**Issue by yiyeluwei** [froger-me/wp-weixin#8]
Hello Alexandre,

I am wondering is there a setting or hooks for h5 in mobile browser to work. Out of the box, I notice that if checkout by mobile browser, it's just like a PC which shows QR code to scan. Thanks.

Chris
Best Regards

**Comment by alexlii1971** [comment]
As for as I know, you can expect 😄

**Comment by ghost** [comment]
Hi Alexandre, this is a great plug-in. Thank You! Combining this with Woo WeChat Pay, it's really handy for WooCommerce. Great Job!

Also have the same question - is the H5 in Mobile Safari / Mobile Chrome now be able to call WeChat Pay directly, or does it shows QR code (similar to desktop version web browser)?

**Comment by froger-me** [comment]
Hello!
I haven't been able to provide support these past few weeks, but I just published a version of all the WP Weixin related plugins, and payment in H5 in mobile browsers is now fully supported!

Please make sure to deactivate all the WP Weixin - related plugins, and update all the plugins to their latest version (v1.3.5), and then reactivate them all :).

**Comment by ghost** [comment]
This is awesome! Thanks for the great work. This plug-in needs very minimal support - thanks to Froger's very clear step by step instructions, and very well written code. Users of this plug-in just need to follow every step, it'd be up-and-running in no time :-)
